image: docker:latest

before_script:
- docker info

build:
  stage: build
  script:
  - docker build -t ubuntu-rust:nightly .
  - docker tag ubuntu-rust:nightly mmrath/ubuntu-rust
  - docker push mmrath/ubuntu-rust