sudo: required

services:
    - docker

script:
    - docker build -t ubuntu-rust:nightly .
    - docker tag ubuntu-rust:nightly mmrath/ubuntu-rust:nightly
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker push mmrath/ubuntu-rust:nightly
